# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]
mainimage: "/assets/img/thumbnail"

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "GitFichas"
description: "Fichas de estudo sobre Git em PortuguÃªs ğŸ‡§ğŸ‡·"
author:      "Jessica Temporal"
