#-------------------------------
# General Site Settings

menu:
- {name: 'Fichas', url: ''}
- {name: 'Blog',     url: 'https://jtemporal.com'}
- {name: 'Sobre',    url: 'about'}
- {name: 'Contato',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: '#005 O que Ã© staging',   url: '005'}
- {name: '#004 Conferindo um commit',   url: '004'}
- {name: '#003 Fazendo um commit',   url: '003'}
- {name: '#002 Adicionando arquivos',   url: '002'}
- {name: '#001 Iniciando um projeto git',   url: '001'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/jesstemporal'}
- {icon: 'instagram', link: 'https://instagram.com/gitfichas'}
- {icon: 'github',    link: 'https://github.com/jtemporal'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/jessicatemporal'}
- {icon: 'envelope',  link: 'mailto:gitfichas@jtemporal.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Fichas de estudo sobre Git em PortuguÃªs ðŸ‡§ðŸ‡·'
  rel-author: 'https://jtemporal.com'
  rel-publisher: 'https://jtemporal.com'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'G-QL2P5KTWT0'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: tru
  disqus_shortname: 'jtemporal'
