#-------------------------------
# General Site Settings

menu:
  pt:
  - {name: 'Fichas', url: ''}
  - {name: 'Blog',     url: 'https://jtemporal.com'}
  - {name: 'Sobre',    url: 'sobre'}
  - {name: 'Contato',  url: 'contato'}
  en:
  - {name: 'Cards', url: 'en'}
  - {name: 'Blog',     url: 'https://jtemporal.com/en'}
  - {name: 'About',    url: 'about'}
  - {name: 'Contact',  url: 'contact'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/jesstemporal'}
- {icon: 'instagram', link: 'https://instagram.com/gitfichas'}
- {icon: 'github',    link: 'https://github.com/jtemporal'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/jessicatemporal'}
- {icon: 'envelope',  link: 'mailto:gitfichas@jtemporal.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  pt:
    description: 'Fichas de estudo sobre Git em PortuguÃªs ðŸ‡§ðŸ‡·'
    rel-author: 'https://jtemporal.com'
    rel-publisher: 'https://jtemporal.com'
  en:
    description: 'Git study cards in English ðŸ‡ºðŸ‡¸'
    rel-author: 'https://jtemporal.com'
    rel-publisher: 'https://jtemporal.com'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'G-QL2P5KTWT0'
